### ISSUE TITLE
docker run has errors on MAC OS

### ISSUE THREAD

**Issue by minnieshi** [databricks/containers#114] opened 2022-11-19 19:49 UTC
it does not seem to support mac os

`$ docker run databricksruntime/standard

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
$`

`Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,1
  Chip:	Apple M1 Pro
`

**Comment by alecglen** [comment] 2023-04-21 21:50
Duplicate of https://github.com/databricks/containers/issues/99

**Comment by xinzhao-db** [comment] 2024-02-07 01:09
close duplicate

**Closed by xinzhao-db** 2024-02-07 01:09 UTC
